project:
  type: book
  output-dir: docs

book:
  title: "Curso ROC: Análisis de datos de eBird utilizando R"
  chapters:
    - index.qmd
    - intror.qmd
  editor:
    mode: source

  page-footer:
    left: "Curso ROC: Análisis de datos de eBird utilizando R"
  site-url: https://ROC-Chile.github.io/r-para-ebird/
  repo-url: https://github.com/ROC-Chile/r-para-ebird
  repo-branch: main
  repo-actions: [edit, issue]

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    author-meta: "Erik Sandvig, Marion Díaz, Vicente Pantoja, Matthew Strimas-Mackey, Tom Auer"

knitr:
  opts_chunk:
    comment: "#>"
    collapse: true
    cache: false
    warn: false
    error: false
    message: false
    out.width: "\\textwidth"
    fig.align: "center"
    fig.show: "hold"
    cache.path: "cache/"
    R.options:
      digits: 3
      knitr.kable.NA: ""
      dplyr.print_min: 6
      dplyr.print_max: 6
